local game_table= {
					{
						["name"]="gameLayer",
						["type"]="CCLayer",
					},
				    {	["name"]="puKeLayer",
						["type"]="CCLayerColor",
					},
					{
						["name"]="oneSprite",
						["type"]="CCSprite",
					},
					{
						["name"]="twoSprite",
						["type"]="CCSprite",
					},
					{
						["name"]="threeSprite",
						["type"]="CCSprite",
					},
					{
						["name"]="fourSprite",
						["type"]="CCSprite",
					},
					{
						["name"]="oneButton",
						["type"]="CCControlButton",
					},
					{
						["name"]="twoButton",
						["type"]="CCControlButton",
					},
					{
						["name"]="threeButton",
						["type"]="CCControlButton",
					},
					{
						["name"]="fourButton",
						["type"]="CCControlButton",
					},
					{
						["name"]="btnChongZhiJiangLi",
						["type"]="CCControlButton",
					},
					
					{--task
						["name"]="nodetask",
						["type"]="CCNode",
					},
					{
						["name"]="labelTaskContent",
						["type"]="CCLabelTTF",
					},
					{
						["name"]="labelTaskAward",
						["type"]="CCLabelTTF",
					},
					{--公告
						["name"]="labelGonggao",
						["type"]="CCLabelTTF",
					},
					{--spriteGonggao
						["name"]="spriteGonggao",
						["type"]="CCSprite",
					},
					{--spriteContent
						["name"]="spriteContent",
						["type"]="CCScale9Sprite",
					},
					{--spriteContent
						["name"]="nodetrum",
						["type"]="CCNode",
					},
					-- {
					-- 	["name"]="nDouble",
					-- 	["type"]="CCLabelTTF",
					-- },
					{
						["name"]="nMoney",
						["type"]="CCLabelTTF",
					},
					{
						["name"]="nDizhu",
						["type"]="CCLabelTTF",
					},
					{
						["name"]="lableLazi",
						["type"]="CCLabelTTF",
					},
					{
						["name"]="nLaizi",
						["type"]="CCLabelTTF",
					},
					{
						["name"]="notRule",
						["type"]="CCSprite",
					},
					{
						["name"]="nodeNoteCards",
						["type"]="CCNode",
					},
					{
						["name"]="nodeLaiZi",
						["type"]="CCNode",
					},
					{
						["name"]="labelTip",
						["type"]="CCLabelTTF",
					},
					{
						["name"]="nodeBtnTips",
						["type"]="CCNode",
					},
					{
						["name"]="spriteBtnTips",
						["type"]="CCSprite",
					},
					{
						["name"]="labelNew1",
						["type"]="CCLabelTTF",
					},
					{
						["name"]="spriteLetterNumber1",
						["type"]="CCSprite",
					},
					{
						["name"]="labelNew2",
						["type"]="CCLabelTTF",
					},
					{
						["name"]="spriteLetterNumber2",
						["type"]="CCSprite",
					},
					
					{
						["name"]="label_game_manage",
						["type"]="CCLabelTTF",
					},
					{
						["name"]="label_game_chat",
						["type"]="CCLabelTTF",
					},
					{
						["name"]="label_game_memory",
						["type"]="CCLabelTTF",
					},
					{
						["name"]="label_game_git",
						["type"]="CCLabelTTF",
					},
					{
						["name"]="spriteVip0",
						["type"]="CCSprite",
					},
					{
						["name"]="spriteVip1",
						["type"]="CCSprite",
					},
					{
						["name"]="spriteVip2",
						["type"]="CCSprite",
					},
					{
						["name"]="spriteHeadImg0",
						["type"]="CCSprite",
					},
					{
						["name"]="spriteHeadImg1",
						["type"]="CCSprite",
					},
					{
						["name"]="spriteHeadImg2",
						["type"]="CCSprite",
					},
					{
						["name"]="layer_game_btn",
						["type"]="CCNode",
					},
					{
						["name"]="layer_game_card",
						["type"]="CCNode",
					},
					{
						["name"]="btn_game_manage",
						["type"]="CCControlButton",
					},
					{
						["name"]="btn_game_chat",
						["type"]="CCControlButton",
					},
					{
						["name"]="btn_game_memory",
						["type"]="CCControlButton",
					},
					{
						["name"]="btn_game_git",
						["type"]="CCControlButton",
					},
					{
						["name"]="btn_changelayer",
						["type"]="CCControlButton",
					},
					-- {
					-- 	["name"]="spriteBeeterSeat",
					-- 	["type"]="CCSprite",
					-- },	
					-- {
					-- 	["name"]="labelBeeterSeat",
					-- 	["type"]="CCLabelTTF",
					-- }				
}
return game_table
