EVENT_ID = EVENT_ID or {};

 EVENT_ID["UPDATE_EVENT_ADD_USER"] =   21        --新玩家加入
 EVENT_ID["UPDATE_EVENT_READY"] = 23             --玩家准备
 EVENT_ID["UPDATE_EVENT_GAME_START"] = 24        --游戏开始
 EVENT_ID["UPDATE_EVENT_REFRESH_CARD"] = 25      --刷新玩家牌
 EVENT_ID["UPDATE_EVENT_CALL_SCORE_REQ"] = 26    --叫分
 EVENT_ID["UPDATE_EVENT_CALL_SCORE_NOT"] = 27    --叫分通知
 EVENT_ID["UPDATE_EVENT_ROB_LORD_REQ"] = 28      --抢地主
 EVENT_ID["UPDATE_EVENT_LORD_CARD"] = 29         --刷新底牌
 EVENT_ID["UPDATE_EVENT_SHOW_CARD_REQ"] = 30     --亮牌请求
 EVENT_ID["UPDATE_EVENT_SHOW_CARD_NOT"] = 31     --亮牌广播
 EVENT_ID["UPDATE_EVENT_PLAY_CARD_REQ"] = 32     --出牌请求
 EVENT_ID["UPDATE_EVENT_PLAY_CARD"] = 33         --出牌
 EVENT_ID["UPDATE_EVENT_COMMON_OP"] = 34         --操作提示
 EVENT_ID["UPDATE_EVENT_CHAT"] = 35              --聊天
 EVENT_ID["UPDATE_EVENT_BOMB"] = 36              --有炸弹...
 EVENT_ID["UPDATE_EVENT_RESULT"] = 37            --游戏结束
 EVENT_ID["UPDATE_EVENT_COMPLETE"] = 38          --断线完整数据
 EVENT_ID["UPDATE_EVETN_TIMER"] = 39             --计时器
 EVENT_ID["UPDATE_EVENT_BASE_TIME"] = 40         --计时器
 EVENT_ID["UPDATE_EVENT_TASK"] = 41              --任务通知
 EVENT_ID["UPDATE_EVENT_COMPLETE_TASK"] = 42     --任务完成通知
 EVENT_ID["UPDATE_EVENT_ONLINE_AWARD"] = 43      --在线时长奖励
 EVENT_ID["UPDATE_EVENT_RANK"] = 44              --战绩排行
 EVENT_ID["UPDATE_EVENT_CHAT_NOT"] = 45          --聊天消息
 EVENT_ID["UPDATE_EVENT_PROP_NOT"] = 46          --道具使用 
 EVENT_ID["UPDATE_EVENT_UPDATE_MONEY"] = 55
 EVENT_ID["UPDATE_EVENT_CHANGE_TABLE"] = 61      --换桌
 EVENT_ID["UPDATE_EVENT_LAIZI"] = 75             --赖子值
 EVENT_ID["pt_cb_ready_req"] = 7308
 EVENT_ID["pt_cg_call_score_ack"] = 5108
 EVENT_ID["pt_cg_rob_lord_ack"] = 5110
 EVENT_ID["pt_cg_play_card_ack"] = 5105
 EVENT_ID["cb_change_table_req"] = 7313
 EVENT_ID["cb_chat_req"] = 7311
 EVENT_ID["cb_send_prop_req"] = 7338
